name: Tests

on: [push, pull_request]

jobs:
    macOS-iOS-tvOS:
        name: macOS/iOS/tvOS
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Make Logs Directory
          run: mkdir logs
        - name: Xcode Version
          run: xcodebuild -version
        - name: XC Pretty
          run: sudo gem install xcpretty-travis-formatter
        - name: Build (macOS/Debug)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-debug.log | xcpretty
        - name: Build (macOS/Release)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-release.log | xcpretty
        - name: Build (iOS/Debug)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-debug.log | xcpretty
        - name: Build (iOS/Release)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
        - name: Build (tvOS/Debug)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-debug.log | xcpretty
        - name: Build (tvOS/Release)
          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatus -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
        - name: Upload Logs
          uses: actions/upload-artifact@v1
          with:
            name: logs
            path: logs
        - name: Slack Notification
          uses: elegantchaos/slatify@master
          if: always()
          with:
            type: ${{ job.status }}
            job_name: 'macOS/iOS/tvOS'
            mention_if: 'failure'
            url: ${{ secrets.SLACK_WEBHOOK }}

